on:
  push:
    branches:
    - main
    - master

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        git_short_sha: ${{ steps.vars.outputs.sha_short }}
